# Generated by Django 5.2.17 on 2026-08-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mp_payment_id", models.CharField(blank=True, max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "comision_plataforma",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "comision_peluquero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "neto_salon",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="appointments.turno",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
