# Generated by Django 5.2.17 on 2026-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="concepto",
            field=models.CharField(
                choices=[("sena", "Seña"), ("total", "Pago total")],
                default="sena",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="mp_preference_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
