# Generated by Django 5.2.17 on 2026-08-15 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.CreateModel(
            name="Barbero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="barberos/"),
                ),
                (
                    "rating_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "disponibilidad_semanal",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ej: {"lun": ["10:00", "19:00"], "mar": ["10:00", "19:00"]}',
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barberos",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="barbero",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "especialidades",
                    models.ManyToManyField(
                        blank=True, related_name="barberos", to="staff.especialidad"
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
