# Generated by Django 5.2.17 on 2026-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de WhatsApp Business del salón, formato E.164",
                        max_length=20,
                    ),
                ),
                (
                    "mp_access_token",
                    models.CharField(
                        blank=True,
                        help_text="Access token de Mercado Pago del salón (Fase 2)",
                        max_length=255,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "Prueba"),
                            ("basico", "Básico"),
                            ("pro", "Pro"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("horario_apertura", models.TimeField(default="09:00")),
                ("horario_cierre", models.TimeField(default="20:00")),
                (
                    "umbral_alerta_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.5,
                        help_text="Si el rating promedio de un peluquero cae debajo de este valor, se genera una alerta",
                        max_digits=3,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
