# Generated by Django 5.2.17 on 2026-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sena_habilitada",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el cliente debe pagar una seña por Mercado Pago para confirmar el turno",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sena_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=30,
                help_text="% del precio del servicio que se cobra como seña",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="mp_access_token",
            field=models.CharField(
                blank=True,
                help_text="Access token (Production o Test) de la cuenta de Mercado Pago del salón",
                max_length=255,
            ),
        ),
    ]
