# Generated by Django 5.2.17 on 2026-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_sena_habilitada_tenant_sena_porcentaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_access_token",
            field=models.CharField(
                blank=True,
                help_text="Access token permanente de la app de Meta para enviar mensajes por este número",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_phone_number_id",
            field=models.CharField(
                blank=True,
                help_text="Phone Number ID de Meta WhatsApp Cloud API (Meta for Developers → WhatsApp → API Setup)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_verify_token",
            field=models.CharField(
                blank=True,
                help_text="Token propio (lo inventás vos) usado para verificar el webhook en Meta for Developers",
                max_length=100,
            ),
        ),
    ]
