# Generated by Django 5.2.17 on 2026-08-15 18:47

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_whatsapp_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="api_key",
            field=models.CharField(
                default=tenants.models._generar_api_key,
                editable=False,
                help_text="Usada por integraciones externas (ej. Forja) para autenticarse contra la API de turnos de este salón",
                max_length=64,
                unique=True,
            ),
        ),
    ]
