# Generated by Django 5.2.17 on 2026-08-15 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="color_primario",
            field=models.CharField(
                default="#e94560",
                help_text="Color de marca del salón en formato hex (ej. #e94560), usado en la mini-web y el panel",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="propietarios",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios que pueden entrar al panel de este salón. Un superusuario ve todos los salones.",
                related_name="salones_propios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
