# Generated by Django 5.2.17 on 2026-08-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_whatsapp_access_token_and_more"),
        ("whatsapp_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversacionWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                (
                    "paso",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("servicio", "Esperando elegir servicio"),
                            ("peluquero", "Esperando elegir peluquero"),
                            ("horario", "Esperando elegir horario"),
                            ("nombre", "Esperando nombre del cliente"),
                            ("confirmar", "Esperando confirmación"),
                            ("finalizado", "Conversación finalizada"),
                        ],
                        default="inicio",
                        max_length=20,
                    ),
                ),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_whatsapp",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "telefono")},
            },
        ),
    ]
