# Generated by Django 5.2.17 on 2026-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="completado_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Se completa solo cuando el turno pasa a estado 'completado', para disparar la solicitud de reseña 2hs después",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="recordatorio_24h_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turno",
            name="recordatorio_2h_enviado",
            field=models.BooleanField(default=False),
        ),
    ]
