# Generated by Django 5.2.17 on 2026-08-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_turno_completado_en_turno_recordatorio_24h_enviado_and_more",
        ),
        ("catalog", "0001_initial"),
        ("staff", "0001_initial"),
        ("tenants", "0005_tenant_color_primario_tenant_propietarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "barbero",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quién atendió la venta, para poder repartir comisión si corresponde",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas_realizadas",
                        to="staff.barbero",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras",
                        to="appointments.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="catalog.producto",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
